[WIP] Feature/230 efo polling refactor
fecgov/fecfile-web-api pull request #1083
Opened 2024-09-12 18:05 UTC by Elaine-Krauss-TCG

[Fecfile#230](https://fecgov.atlassian.net/browse/FECFILE-230)

2024-09-23 15:53 UTC, dheitzer requested changes
Looks nice! only things is - are the changes to [performance-testing/bulk-testing-data-fixture-generator.py](https://github.com/fecgov/fecfile-web-api/pull/1083/files#diff-e7d1f1ce5369d88d0a406247d6e408421e59d3b0656e869ba3ef5e3a95a9c879) for another ticket? they seem unrelated. 

Also, it might be worth putting in the original ticket (230) a comment about what requirements were determined with FEC relating to this ticket.

2024-09-30 14:02 UTC, toddlees submitted a review, later dismissed

2024-10-02 19:23 UTC, Elaine-Krauss-TCG commented
> Looks nice! only things is - are the changes to [performance-testing/bulk-testing-data-fixture-generator.py](https://github.com/fecgov/fecfile-web-api/pull/1083/files#diff-e7d1f1ce5369d88d0a406247d6e408421e59d3b0656e869ba3ef5e3a95a9c879) for another ticket? they seem unrelated.

Good question.  In order to generate a sufficiently large dotFEC file within a reasonable timeframe, I needed to add memo texts to every transaction.  I added additional functionality to this script in order to make that process quicker.

2024-10-02 19:27 UTC, Elaine-Krauss-TCG commented on django-backend/fecfiler/settings/base.py
> +EFO_POLLING_INTERVAL = get_float_from_string(
The idea here is that this is the fallback for converting the string value of the environment variable into a float.  Given the next request, though, this is unnecessary.

2024-10-02 19:37 UTC, Elaine-Krauss-TCG commented on django-backend/fecfiler/shared/utilities.py
> +    except Exception:
Changed!  It now raises an error when the server spins up with a provided value for these environment variables that cannot be converted to a float.

![image](https://github.com/user-attachments/assets/803634e8-2e4b-4860-b384-23047cde39c3)

2024-10-02 19:39 UTC, Elaine-Krauss-TCG commented on django-backend/fecfiler/web_services/tasks.py
> +                submission.fec_status = FECStatus.FAILED
Great idea :+1:

2024-10-02 19:46 UTC, Elaine-Krauss-TCG commented on django-backend/fecfiler/web_services/test_tasks.py
> +class TestWebPrintSubmitter(WebPrintSubmitter):
I changed it to UnitTestWebPrintSubmitter which is at least a little bit better.  `AlwaysProcessingWebPrintSubmitter` would be great, except the behavior here is _very_ specific to what's needed for testing.  I've added a comment to explain the behavior.

2024-10-02 20:19 UTC, Elaine-Krauss-TCG commented
> Also, it might be worth putting in the original ticket (230) a comment about what requirements were determined with FEC relating to this ticket.

@dheitzer We determined in a prior weekly dev meeting that, for this ticket, we'll set things up so that the values can be configured with environment variables, and then we'll get the specifics of the requirements in the future.  As long as that's still good with @lbeaufort then we _should_ be good.

2024-10-02 22:42 UTC, lbeaufort commented
> @dheitzer We determined in a prior weekly dev meeting that, for this ticket, we'll set things up so that the values can be configured with environment variables, and then we'll get the specifics of the requirements in the future. As long as that's still good with @lbeaufort then we _should_ be good.

@Elaine-Krauss-TCG I think since this dev work is complete, we should move it forward/merge the changes and can tweak the config once we get additional requirements.

2024-10-03 19:41 UTC, dheitzer approved these changes

2024-10-07 16:01 UTC, sasha-dresden approved these changes

2024-10-07 16:04 UTC, merged