feature/1612 - Make sure report_code_label makes it onto get_queryset override so it…
fecgov/fecfile-web-api pull request #1086
Opened 2024-09-16 14:48 UTC by sasha-dresden

Issue [FECFILE-1612](https://fecgov.atlassian.net/browse/FECFILE-1612)

2024-09-17 12:56 UTC, Elaine-Krauss-TCG approved these changes

2024-09-17 14:54 UTC, toddlees requested changes

2024-09-17 19:26 UTC, sasha-dresden commented on django-backend/fecfiler/reports/views.py
>          ordering_whens = [
Ah good point. I did try just getting rid of the queryset but it complained about that so I just left it alone. Looking at the way we handled transactions, I did it the same way here.

2024-09-17 19:26 UTC, sasha-dresden commented on django-backend/fecfiler/reports/views.py
> +        whens = [When(form_type=k, then=Value(v)) for k, v in version_labels.items()]
You're right, that is a bit confusing when we have multiple when conditionals. Updated to use your suggestion.

2024-09-18 12:48 UTC, toddlees approved these changes

2024-09-18 12:48 UTC, merged