feature/1591 - Add dotfec unit tests for Form 1M
fecgov/fecfile-web-api pull request #1137
Opened 2024-10-17 21:23 UTC by sasha-dresden

Issue [FECFILE-1591](https://fecgov.atlassian.net/browse/FECFILE-1591)

2024-10-18 20:47 UTC, Elaine-Krauss-TCG approved these changes

2024-10-21 18:48 UTC, toddlees requested changes

2024-10-21 18:48 UTC, toddlees commented on django-backend/fecfiler/web_services/dot_fec/tests/dot_fec_record_testing/test_form_f1m.py
> +        self.assertEqual(self.split_row[63], "20240108")
that is, 51st contributor and original registration are swapped

2024-10-22 14:40 UTC, sasha-dresden commented on django-backend/fecfiler/web_services/dot_fec/tests/dot_fec_record_testing/test_form_f1m.py
> +        self.assertEqual(self.split_row[63], "20240108")
Good catch! I went through looking for any other issues but that was the only one I could find for Form 1M. There might be some issues in other forms/transaction types. I'm going to go through those in the other tickets, but for this one I put a Validate PR in to fix it and updated the API PR to use the new one.

2024-10-22 21:01 UTC, toddlees approved these changes
great work! this gives me a lot of confidence in our .fec compilation

2024-10-22 21:01 UTC, merged