feature/1776 - Update requirements.txt and requirements-test.txt to reflect currently used dependencies
fecgov/fecfile-web-api pull request #1231
Opened 2024-12-02 21:17 UTC by sasha-dresden

Issue [FECFILE-1776](https://fecgov.atlassian.net/browse/FECFILE-1776)

Also after the dev meetup it's believed django storages is no longer required, so I removed it from the INSTALLED_APPS list. This didn't cause any breaking changes locally, and shouldn't once it goes to dev, but just something to keep an eye out for.

2024-12-03 15:03 UTC, dheitzer requested changes
Briefly checking it seems the following are not used:
```
retry
rich
django-otp
```
Seems that deptry is not picking up these (and maybe other) unused dependencies - I might suggest checking for them manually.

Also, would we want to take this opportunity to upgrade some of the requirements-test.txt at least? For example, flake8 is quite out of date.

2024-12-03 17:16 UTC, lbeaufort requested changes
I'd like to keep our builds more deterministic, and keep our pinned patch versions. ie
`==` instead of `~=`

2024-12-03 18:25 UTC, sasha-dresden commented on requirements.txt
> -# Pinning sqlparse to 0.5.0 as it is a sub-dependency that needs to be upgraded for security
Updated so everything is == instead of ~=

2024-12-09 19:40 UTC, sasha-dresden commented
Closing. This will be handled as part of [PR1244](https://github.com/fecgov/fecfile-web-api/pull/1244) which does this and sets up the deptry circle task.

2024-12-09 19:40 UTC, closed without merging