[WIP] Feature/1866 check migrations for downtime
fecgov/fecfile-web-api pull request #1245
Opened 2024-12-09 14:52 UTC by lbeaufort

Ticket link: https://fecgov.atlassian.net/browse/FECFILE-1866
  
Related PRs:

2024-12-18 16:50 UTC, sasha-dresden approved these changes
This looks good. I was a little concerned about the git commit being used and thinking we might need to keep updating it, but I looked it up and remembered you were setting it to only lint migrations AFTER that commit so no need to ever update it.

2024-12-19 16:18 UTC, dheitzer approved these changes

2024-12-31 19:00 UTC, Elaine-Krauss-TCG requested changes, later dismissed
![image](https://github.com/user-attachments/assets/8cbbbb4e-2bce-4b2b-a5d5-7a25cdf0a3f1)

In a [PR that I set up to test this](https://github.com/fecgov/fecfile-web-api/pull/1267), the migration linter identified that a (test) migration was not reversible, but it failed to raise an error in the CircleCI test as a whole.

2025-01-03 15:10 UTC, toddlees commented
> ![image](https://private-user-images.githubusercontent.com/104506225/399515226-8cbbbb4e-2bce-4b2b-a5d5-7a25cdf0a3f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5MTcyMDQsIm5iZiI6MTczNTkxNjkwNCwicGF0aCI6Ii8xMDQ1MDYyMjUvMzk5NTE1MjI2LThjYmJiYjRlLTJiY2UtNGIyYi1hNWQ1LTdhMjVjZGYwYTNmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwM1QxNTA4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDUyN2ZjMmViMjAzMjZhNzA0NTE4MDMzMWUzYjZjYmM4Yjc5OGI0MDEwYWVjOTI5NTE1YzcwZDFhMGNmZGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sqBXJNZONNwWTbRnS1ogx-TowJijnxLH3HuM79DgdvM)
> 
> In a [PR that I set up to test this](https://github.com/fecgov/fecfile-web-api/pull/1267), the migration linter identified that a (test) migration was not reversible, but it failed to raise an error in the CircleCI test as a whole.

@Elaine-Krauss-TCG looks like those two are warnings rather than errors

2025-01-03 15:10 UTC, toddlees approved these changes

2025-01-03 18:14 UTC, merged