[WIP] Feature/e2e login route
fecgov/fecfile-web-api pull request #228
Opened 2022-09-14 13:31 UTC by Elaine-Krauss-TCG

[#557](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/557)

The direct login API has been cleaned up and stripped down to the basics.  The url will not be available unless a specific setting is enabled.  This setting is enabled on local and in a new E2E settings file.

2022-09-14 18:58 UTC, dheitzer approved these changes

2022-09-14 22:25 UTC, mjtravers approved these changes

2022-09-28 13:25 UTC, toddlees requested changes

2022-09-28 13:38 UTC, toddlees commented on django-backend/fecfiler/authentication/authenticate_login.py
> +def update_last_login_time(account):
This is SO much better!!

2022-09-28 13:47 UTC, Elaine-Krauss-TCG commented on django-backend/fecfiler/settings/base.py
> +E2E_TESTING_LOGIN = True
This has been addressed, but for some reason the code preview didn't update...

2022-09-28 13:49 UTC, Elaine-Krauss-TCG commented
The dependency check is failing due to circumstances outside of this branch

2022-09-28 20:50 UTC, merged