Feature/237 aggregation groups
fecgov/fecfile-web-api pull request #240
Opened 2022-10-07 20:14 UTC by Elaine-Krauss-TCG

#237

2022-10-11 15:27 UTC, dheitzer approved these changes

2022-10-11 16:37 UTC, mjtravers requested changes
One small file formatting requests and one other not so small request:
I think it would be better to use more computer friendly identifiers for the group IDs. Similar to the ones we use for the transaction type identifiers, that is all caps and underscores. This request will, of course, affect the code in all 3 repos

2022-10-11 16:37 UTC, mjtravers commented on django-backend/fecfiler/scha_transactions/migrations/0027_scha_transaction_aggregation_group.py
> +tid_to_aggregation_groups = {'INDIVIDUAL_RECEIPT': general, 'TRIBAL_RECEIPT': general, 'EARMARK_RECEIPT': general, 'EARMARK_MEMO': general, 'PARTY_RECEIPT': general, 'PAC_RECEIPT': general, 'PAC_EARM
Let's line wrap each entry for better readability

2022-10-12 13:36 UTC, toddlees approved these changes

2022-10-12 14:06 UTC, merged