Feature/477 partnership receipt
fecgov/fecfile-web-api pull request #323
Opened 2023-01-11 22:51 UTC by mjtravers

#477

2023-01-13 15:35 UTC, Elaine-Krauss-TCG approved these changes

2023-01-25 18:57 UTC, dheitzer approved these changes

2023-01-26 15:46 UTC, toddlees requested changes

2023-01-26 15:46 UTC, toddlees commented on django-backend/fecfiler/transactions/schedule_a/serializers.py
> +                grandparent = ScheduleATransaction.objects.get(
You'll need to refer to the Transactions model or ScheduleA model now with the 316 code that went into develop.

I notice that we've split 371(parent-child updates) functionality between the front ent (parent updates child) and back end (child updates parent).  Is it possible to not split the updating brain across repos?

If we want to keep it client side, we could just have the client fetch the parent before saving and post the updates together.

2023-01-27 17:28 UTC, mjtravers commented
This PR was merged into PR for #330  and is now OBE

2023-01-27 17:28 UTC, closed without merging