[WIP] Feature/808 dsp lines 11 and 33 column b
fecgov/fecfile-web-api pull request #383
Opened 2023-03-23 13:12 UTC by Elaine-Krauss-TCG

[App#808](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/808)

2023-03-28 22:16 UTC, mjtravers requested changes
@Elaine-Krauss-TCG Per the DEV notes in the ticket, the transactions_transaction table needs an index on the form_type column.

2023-03-29 14:41 UTC, mjtravers approved these changes

2023-03-29 19:16 UTC, toddlees requested changes
Just noticed some weirdness with the test_summary_transactions for SA17.  There are multiple transactions with the id: "a12aefe8-9b5f-4539-b7e5-170000000004". I think that might be tripping up some of the expectations

2023-03-31 13:20 UTC, toddlees approved these changes

2023-03-31 13:23 UTC, Elaine-Krauss-TCG commented
> Just noticed some weirdness with the test_summary_transactions for SA17. There are multiple transactions with the id: "a12aefe8-9b5f-4539-b7e5-170000000004". I think that might be tripping up some of the expectations

Thankfully, no changes to the unit tests were necessary, but it was worthwhile to change the id's in the fixture because there was a genuinely high chance of their overlap causing unexpected behavior

2023-03-31 17:09 UTC, mjtravers approved these changes

2023-03-31 17:10 UTC, merged