Feature/1386 calendar ytd
fecgov/fecfile-web-api pull request #557
Opened 2023-10-16 13:30 UTC by Elaine-Krauss-TCG

[#1386](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-app/1386)

2023-10-16 14:12 UTC, dheitzer commented on django-backend/fecfiler/transactions/views.py
> +            missing_params.append("and either contact_1_id or candidate_id")
might remove 'and' as this could be confusing if only this is needed

2023-10-16 15:14 UTC, Elaine-Krauss-TCG commented on django-backend/fecfiler/transactions/managers.py
> +    def get_candidate_contact_clause(self):
Oh...  Well that _massively_ simplifies a few things...

2023-10-17 16:54 UTC, Elaine-Krauss-TCG commented on django-backend/fecfiler/transactions/managers.py
> +                candidate_contact_clause,
Done

2023-10-17 16:55 UTC, Elaine-Krauss-TCG commented on django-backend/fecfiler/transactions/views.py
>      def previous(self, request):
:+1:  I've got everything separated out into different endpoints now

2023-10-19 14:16 UTC, toddlees requested changes

2023-10-20 13:33 UTC, toddlees approved these changes
Great job with this!  You handle a bunch of edge cases.  this will serve us well

2023-10-20 17:53 UTC, merged