feature/858 - Update sorting to be by line_label as front end uses line_label, not line_label_order_key
fecgov/fecfile-web-api pull request #867
Opened 2024-04-30 19:15 UTC by sasha-dresden

Issue: #858

2024-05-01 14:56 UTC, Elaine-Krauss-TCG approved these changes

2024-05-01 19:38 UTC, dheitzer approved these changes

2024-05-07 21:02 UTC, mjtravers requested changes
It looks like the LINE_LABEL_ORDER_CLAUSE and line_label_order_key in the transaction manager are OBE. Please review and remove that code if true.

2024-05-10 14:05 UTC, Elaine-Krauss-TCG approved these changes

2024-05-13 16:25 UTC, mjtravers approved these changes

2024-05-13 16:25 UTC, merged